"""make orders.source not nullable

Revision ID: 0668c1ecf35c
Revises: ebe63b373cf2
Create Date: 2026-08-18 21:36:16.503352

"""
from alembic import op
import sqlalchemy as sa


revision = '0668c1ecf35c'
down_revision = 'ebe63b373cf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
