"""add price to products

Revision ID: 1dc37d21bee7
Revises: 800d90d6efd5
Create Date: 2026-08-18 14:33:33.343330

"""
from alembic import op
import sqlalchemy as sa


revision = '1dc37d21bee7'
down_revision = '800d90d6efd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
