"""add source to orders

Revision ID: ebe63b373cf2
Revises: 1dc37d21bee7
Create Date: 2026-08-18 20:51:52.334185

"""
from alembic import op
import sqlalchemy as sa


revision = 'ebe63b373cf2'
down_revision = '1dc37d21bee7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'source')
    # ### end Alembic commands ###
